name: Build and Test C# Project (Framework 4.7.2)


on:
  workflow_dispatch:
  push:
    branches: [ master ]  # 触发条件，当main分支有push时触发
  pull_request:
    branches: [ master ]  # 当向main分支发起pull request时也触发

jobs:
  build:

    runs-on: windows-latest  # 使用Windows环境，因为.NET Framework在Windows上运行

    env:
      MELONLOADER_REPO: https://api.github.com/repos/LavaGang/MelonLoader/releases/latest
      MELONLOADER_ASSET_NAME: MelonLoader.x64.zip
      OUTPUT_URL: ${{ secrets.OUTPUT_URL }}
      OUTPUT_FILE: Output.7z

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: scripts
      run: |
                choco install 7zip.install -y
                mkdir cache
                Invoke-WebRequest -Uri https://github.com/LavaGang/MelonLoader/releases/download/v0.6.5/MelonLoader.x64.zip -OutFile "$(Get-Location)\cache\MelonLoader.x64.zip"        
                7z x "$(Get-Location)\cache\MelonLoader.x64.zip" -o"$(Get-Location)\Out"     
                Invoke-WebRequest -Uri ${{ secrets.OUTPUT_URL }} -OutFile "$(Get-Location)\cache\Output.7z"
                7z x "$(Get-Location)\cache\Output.7z" -o"$(Get-Location)\Output"

                @"
                namespace SinmaiAssist {
                    public static partial class BuildInfo {
                        public const string CommitHash = "$(git rev-parse --short HEAD)";
                        public const string BuildDate = "$(Get-Date -Format 'o')";
                    }
                }
                "@ | Out-File -FilePath ".\BuildInfo.cs" -Encoding ascii
                
                dotnet build
                mkdir ".\Out\Mods\"
                mkdir ".\Out\UserLibs\"
                mkdir ".\Out\Sinmai-Assist\"
                cmd /c copy /y ".\Output\Sinmai-Assist.dll" ".\Out\Mods\Sinmai-Assist.dll"
                cmd /c copy /y ".\Output\YamlDotNet.dll" ".\Out\UserLibs\YamlDotNet.dll"
                cmd /c copy /y ".\config - zh_CN.yml" ".\Out\Sinmai-Assist\config.yml"
                
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SinmaiAssist_build_${{ github.sha }}
        path: Out
        make_latest: true
        files: Out.zip
